title:  Muhammad Waseem blog
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Contemplation of an Undergrad's knowledge
baseurl: "/blogs" # the subpath of your site, e.g. /blog
url: "https://hwaseem04.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hwaseem04
github_username:  hwaseem04

# Build settings

# Coverted to regular theme
theme: minima
plugins:
  - jekyll-feed
gem:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
